# Config file for GFlows.
# See https://github.com/jbrunton/gflows/wiki/Configuration for options.
githubDir: github-sample
templates:
  engine: ytt
  defaults:
    libs:
      - workflow-configuration/build-publish
      - libs
    dependencies:
      - https://raw.githubusercontent.com/CoverGo/ci-workflow-libraries/v1.5.2/.gflows

